package com.villagerentals.dao;

import com.villagerentals.model.Rental;
import java.sql.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class RentalDAO {

    /**
     * Get all rentals from the database.
     */
    public List<Rental> getAll() {
        List<Rental> rentals = new ArrayList<>();
        String sql = "SELECT rental_id, date, customer_id, equipment_id, rental_date, return_date, cost FROM rentals ORDER BY rental_id";

        try (Connection conn = DatabaseManager.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                Rental rental = new Rental(
                    rs.getInt("rental_id"),
                    LocalDate.parse(rs.getString("date")),
                    rs.getInt("customer_id"),
                    rs.getInt("equipment_id"),
                    LocalDate.parse(rs.getString("rental_date")),
                    LocalDate.parse(rs.getString("return_date")),
                    rs.getDouble("cost")
                );
                rentals.add(rental);
            }
        } catch (SQLException e) {
            System.err.println("Error getting rentals: " + e.getMessage());
        }
        return rentals;
    }

    /**
     * Add a new rental to the database.
     * The rental_id is auto-generated by the database.
     * Returns true if successful.
     */
    public boolean add(Rental rental) {
        String sql = "INSERT INTO rentals (date, customer_id, equipment_id, rental_date, return_date, cost) VALUES (?, ?, ?, ?, ?, ?)";

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, rental.getDate().toString());
            pstmt.setInt(2, rental.getCustomerId());
            pstmt.setInt(3, rental.getEquipmentId());
            pstmt.setString(4, rental.getRentalDate().toString());
            pstmt.setString(5, rental.getReturnDate().toString());
            pstmt.setDouble(6, rental.getCost());
            pstmt.executeUpdate();
            return true;
        } catch (SQLException e) {
            System.err.println("Error adding rental: " + e.getMessage());
            return false;
        }
    }

    /**
     * Get all rentals for a specific customer.
     */
    public List<Rental> getByCustomer(int customerId) {
        List<Rental> rentals = new ArrayList<>();
        String sql = "SELECT rental_id, date, customer_id, equipment_id, rental_date, return_date, cost FROM rentals WHERE customer_id = ? ORDER BY rental_id";

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, customerId);
            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                Rental rental = new Rental(
                    rs.getInt("rental_id"),
                    LocalDate.parse(rs.getString("date")),
                    rs.getInt("customer_id"),
                    rs.getInt("equipment_id"),
                    LocalDate.parse(rs.getString("rental_date")),
                    LocalDate.parse(rs.getString("return_date")),
                    rs.getDouble("cost")
                );
                rentals.add(rental);
            }
        } catch (SQLException e) {
            System.err.println("Error getting rentals by customer: " + e.getMessage());
        }
        return rentals;
    }

    /**
     * Check how many rentals exist.
     */
    public int count() {
        String sql = "SELECT COUNT(*) FROM rentals";

        try (Connection conn = DatabaseManager.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            if (rs.next()) {
                return rs.getInt(1);
            }
        } catch (SQLException e) {
            System.err.println("Error counting rentals: " + e.getMessage());
        }
        return 0;
    }
}
